config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'covers/show'
  resources :books
  devise_for :users
  root to: "pages#home"
  get 'covers/:filename', to: 'covers#show', as: :cover
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord

  attribute :cover_url
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!

  # Helpers
  include BookHelper
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  include BookHelper

  # GET /books or /books.json
  def index
    @books = Book.order(:id)
    @books = filter_books(params[:character]) if params[:character].present?
  end

  # GET /books/1 or /books/1.json
  def show
  end

  # GET /books/new
  def new
    @book = Book.new
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    @book = Book.new(book_params)

    respond_to do |format|
      if @book.save
        format.html { redirect_to book_url(@book), notice: "Book was successfully created." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to book_url(@book), notice: "Book was successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy!

    respond_to do |format|
      format.html { redirect_to books_url, notice: "Book was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:title, :year, :read, :cover_path, :cover_url)
    end

    def filter_books(character)
      case character
      when "Hercule Poirot"
        Book.where("title LIKE ?", "%Hercule Poirot%").order(:title)
      when "Miss Marple"
        Book.where("title LIKE ?", "%Miss Marple%").order(:title)
      # Ajoutez d'autres filtres ici pour d'autres personnages
      else
        Book.none
      end
    end
end

app/controllers/covers_controller.rb
class CoversController < ApplicationController
  def show
    cover_path = Rails.root.join('app', 'assets','images', 'covers', params[:filename])


    puts cover_path
    # Envoie le fichier image en réponse
    send_file cover_path, type: 'image/jpeg', disposition: 'inline'
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [ :home ]
  include BookHelper

  def home
    @books = Book.order(:id)
    @books = filter_books(params[:character]) if params[:character].present?
  end

  private

  def filter_books(character)
    Book.where('title LIKE ?', "#{character}%").order(:title)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_helper.rb
# app/helpers/book_helper.rb
module BookHelper
  def cover_valid?(cover_url)
    begin
      response = Net::HTTP.get_response(URI.parse(cover_url))
      return response.is_a?(Net::HTTPSuccess)
    rescue
      return false
    end
  end
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Year:</strong>
    <%= book.year %>
  </p>

  <p>
    <strong>Read:</strong>
    <%= book.read %>
  </p>

  <p>
    <strong>Cover url:</strong>
    <%= book.cover_url %>
  </p>

</div>

app/views/books/_form.html.erb
<%= simple_form_for(@book) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :year %>
    <%= f.input :read %>
    <%= f.input :cover_url %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/books/edit.html.erb
<div class="container">
  <h1>Editing book</h1>

  <%= render "form", book: @book %>

  <br>

  <div>
    <%= link_to "Show this book", @book %> |
    <%= link_to "Back to books", books_path %>
  </div>
</div>

app/views/books/index.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <h1>Books</h1>

  <div id="books">
    <% @books.each do |book| %>
      <%= render book %>
      <p>
        <%= link_to "Show this book", book, class: 'btn btn-gradient rounded-pill' %>
      </p>
    <% end %>
  </div>

  <%= link_to "New book", new_book_path %>
</div>

app/views/books/new.html.erb
<h1>New book</h1>

<%= render "form", book: @book %>

<br>

<div>
  <%= link_to "Back to books", books_path %>
</div>

app/views/books/show.html.erb
<div class="container">
  <p style="color: green"><%= notice %></p>

  <%= render @book %>

  <div>
    <%= link_to "Edit this book", edit_book_path(@book), class: "btn btn-success rounded-pill" %> |
    <%= link_to "Back to books", books_path, class: "btn btn-warning rounded-pill" %>
  </div>
</div>

app/views/covers/show.html.erb
<h1>Covers#show</h1>
<p>Find me in app/views/covers/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AgathaChristieBooks</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body><%= render "shared/navbar" %>
<%= render "shared/flashes" %>

    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<div class="container" data-controller="read-checkbox">
  <div class="grid-container">
    <% @books.each_slice(4) do |row| %>
      <div class="grid-row">
        <% row.each do |book| %>
          <div class="grid-item">
            <%= content_tag :p, book.title, class: "book-title" %>
            <% if book.cover_url.present? %>
              <%= image_tag book.cover_url, class: "book-cover" %>
            <% end %>
            <div class="field">
              <%= check_box_tag "read_#{book.id}", 1, book.read, data: { url: book_path(book), target: "read-checkbox.checkbox" }, class: "read-checkbox" %>
              <%= label_tag "read_#{book.id}", book.read ? "Lu" : "À lire", data: { target: "read-checkbox.label" } %>
            </div>
          </div>
        <% end %> <!-- row.each -->
      </div>
    <% end %> <!-- @books.each_slice -->
  </div> <!-- grid-container -->
</div> <!-- container -->

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
          <a href="#" class="avatar" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar", alt: "dropdown menu" %>
          </a>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>